import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomBytes } from 'node:crypto';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import Handlebars from 'handlebars';
import { paths, profileExists, readState, updateState } from '../config/paths.js';
import { defaultImage } from '../docker/image.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TEMPLATE_DIR = join(__dirname, '..', '..', '..', 'templates');

export const DEFAULT_CLAUDE_PROFILE = 'claude';
export const DEFAULT_CLAUDE_PORT = 8000;

/**
 * Materialize a ready-to-serve two-container default profile for Claude Code
 * (complexity classifier + Brick router) if it does not exist yet.
 *
 * - config.yaml is copied verbatim from the baked template so the
 *   `anthropic_passthrough` block (stripped by ConfigSchema) is preserved.
 * - docker-compose.yml uses claude-default.docker-compose.yaml.hbs (2 services).
 * - .env is written with a freshly-generated BRICK_CLASSIFIER_TOKEN.
 *
 * Returns the profile name.
 */
export async function ensureDefaultProfile(): Promise<string> {
  const profile = DEFAULT_CLAUDE_PROFILE;
  if (profileExists(profile)) return profile;

  const pp = paths(profile);
  mkdirSync(pp.profileDir, { recursive: true, mode: 0o700 });

  // 1. Config (verbatim copy — preserves anthropic_passthrough block).
  const configTemplate = readFileSync(join(TEMPLATE_DIR, 'claude-default.config.yaml'), 'utf8');
  writeFileSync(pp.config, configTemplate, { mode: 0o600 });

  // 2. .env — random classifier bearer token (never leaves the local network).
  const classifierToken = randomBytes(32).toString('hex');
  writeFileSync(
    pp.env,
    `# Brick default Claude profile — generated by brick claude on.\n` +
    `# No provider API key needed: the client's Anthropic bearer is forwarded verbatim.\n` +
    `BRICK_CLASSIFIER_TOKEN=${classifierToken}\n`,
    { mode: 0o600 }
  );

  // 3. docker-compose.yml — two-container template (classifier + router).
  const composeTpl = readFileSync(join(TEMPLATE_DIR, 'claude-default.docker-compose.yaml.hbs'), 'utf8');
  const composeRendered = Handlebars.compile(composeTpl)({
    projectName: `brick-${profile}`,
    port: DEFAULT_CLAUDE_PORT,
    configPath: pp.config,
    useLocalClassifier: true,   // default profile ships the local classifier sidecar
    image: defaultImage(),   // unused by this template but kept for parity
  });
  writeFileSync(pp.compose, composeRendered, { mode: 0o644 });

  if (!readState().activeProfile) updateState({ activeProfile: profile });

  return profile;
}
