import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomBytes } from 'node:crypto';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import Handlebars from 'handlebars';
import { paths, profileExists, readState, updateState } from '../config/paths.js';
import { defaultImage } from '../docker/image.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TEMPLATE_DIR = join(__dirname, '..', '..', '..', 'templates');

export const DEFAULT_CLAUDE_PROFILE = 'claude';
export const DEFAULT_CLAUDE_PORT = 8000;

/**
 * Materialize a ready-to-serve default profile for Claude Code. By default the
 * complexity classifier is hosted on Regolo (no local sidecar), so the profile
 * is a single router container; the user supplies their Regolo API key (see
 * `brick claude on`, which prompts for it on first run). A self-hosted local
 * classifier remains one command away: `brick claude settings compute local`.
 *
 * - config.yaml is copied verbatim from the baked template so the
 *   `anthropic_passthrough` block (stripped by ConfigSchema) is preserved.
 * - docker-compose.yml uses claude-default.docker-compose.yaml.hbs, rendered
 *   without the classifier sidecar (useLocalClassifier: false).
 * - .env is seeded with an empty REGOLO_API_KEY placeholder and a
 *   BRICK_CLASSIFIER_TOKEN (still used if the user later switches to local).
 *
 * Returns the profile name.
 */
export async function ensureDefaultProfile(): Promise<string> {
  const profile = DEFAULT_CLAUDE_PROFILE;
  if (profileExists(profile)) return profile;

  const pp = paths(profile);
  mkdirSync(pp.profileDir, { recursive: true, mode: 0o700 });

  // 1. Config (verbatim copy — preserves anthropic_passthrough block).
  const configTemplate = readFileSync(join(TEMPLATE_DIR, 'claude-default.config.yaml'), 'utf8');
  writeFileSync(pp.config, configTemplate, { mode: 0o600 });

  // 2. .env — REGOLO_API_KEY placeholder (filled in by `brick claude on` on
  //    first run) plus a random BRICK_CLASSIFIER_TOKEN kept for the local
  //    classifier path, so switching to local compute later needs no new secret.
  const classifierToken = randomBytes(32).toString('hex');
  writeFileSync(
    pp.env,
    `# Brick default Claude profile — generated by brick claude on.\n` +
    `# REGOLO_API_KEY authenticates the hosted complexity classifier\n` +
    `# (brick-complexity-pro on api.regolo.ai). Get a key at https://regolo.ai/signup\n` +
    `REGOLO_API_KEY=\n` +
    `# Used only if you switch to a local classifier (brick claude settings compute local).\n` +
    `BRICK_CLASSIFIER_TOKEN=${classifierToken}\n`,
    { mode: 0o600 }
  );

  // 3. docker-compose.yml — single-container template (router only); the
  //    hosted Regolo classifier means no local sidecar.
  const composeTpl = readFileSync(join(TEMPLATE_DIR, 'claude-default.docker-compose.yaml.hbs'), 'utf8');
  const composeRendered = Handlebars.compile(composeTpl)({
    projectName: `brick-${profile}`,
    port: DEFAULT_CLAUDE_PORT,
    configPath: pp.config,
    useLocalClassifier: false,   // default profile uses the hosted Regolo classifier
    image: defaultImage(),
  });
  writeFileSync(pp.compose, composeRendered, { mode: 0o644 });

  if (!readState().activeProfile) updateState({ activeProfile: profile });

  return profile;
}
