import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomBytes } from 'node:crypto';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import Handlebars from 'handlebars';
import { paths, profileExists, readState, updateState } from '../config/paths.js';
import { defaultImage } from '../docker/image.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TEMPLATE_DIR = join(__dirname, '..', '..', '..', 'templates');

export const DEFAULT_CODEX_PROFILE = 'codex';
// The two-container compose template maps host {{port}} -> container :8000, so
// the router always listens on 8000 internally. The Codex profile reuses host
// port 8000; its config server_port matches. This means the Codex and Claude
// router stacks are mutually exclusive on the host (only one can bind 8000 at a
// time) — `brick codex on` warns and asks to stop the other stack if it is up.
export const DEFAULT_CODEX_PORT = 8000;

/**
 * Materialize a ready-to-serve default profile for OpenAI Codex. Like the
 * Claude default, the complexity classifier is hosted on Regolo by default
 * (no local sidecar); the user supplies their Regolo API key. Switch to a
 * self-hosted local classifier with `brick codex settings compute local`.
 * The router runs the full skill router over the OpenAI pool and forwards via
 * /v1/chat/completions. Returns the profile name.
 */
export async function ensureDefaultCodexProfile(): Promise<string> {
  const profile = DEFAULT_CODEX_PROFILE;
  if (profileExists(profile)) return profile;

  const pp = paths(profile);
  mkdirSync(pp.profileDir, { recursive: true, mode: 0o700 });

  // 1. Config (verbatim copy — preserves the skill_router + dynamic_effort block).
  const configTemplate = readFileSync(join(TEMPLATE_DIR, 'codex-default.config.yaml'), 'utf8');
  writeFileSync(pp.config, configTemplate, { mode: 0o600 });

  // 2. .env — REGOLO_API_KEY placeholder (filled by `brick codex on` on first
  //    run) + a BRICK_CLASSIFIER_TOKEN kept for the local classifier path.
  const classifierToken = randomBytes(32).toString('hex');
  writeFileSync(
    pp.env,
    `# Brick default Codex profile — generated by brick codex on.\n` +
    `# REGOLO_API_KEY authenticates the hosted complexity classifier\n` +
    `# (brick-complexity-pro on api.regolo.ai). Get a key at https://regolo.ai/signup\n` +
    `REGOLO_API_KEY=\n` +
    `# Used only if you switch to a local classifier (brick codex settings compute local).\n` +
    `BRICK_CLASSIFIER_TOKEN=${classifierToken}\n`,
    { mode: 0o600 }
  );

  // 3. docker-compose.yml — reuse the shared template (router only; the hosted
  //    Regolo classifier means no local sidecar).
  const composeTpl = readFileSync(join(TEMPLATE_DIR, 'claude-default.docker-compose.yaml.hbs'), 'utf8');
  const composeRendered = Handlebars.compile(composeTpl)({
    projectName: `brick-${profile}`,
    port: DEFAULT_CODEX_PORT,
    configPath: pp.config,
    useLocalClassifier: false,   // default profile uses the hosted Regolo classifier
    image: defaultImage(),
  });
  writeFileSync(pp.compose, composeRendered, { mode: 0o644 });

  if (!readState().activeProfile) updateState({ activeProfile: profile });

  return profile;
}
