import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomBytes } from 'node:crypto';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import Handlebars from 'handlebars';
import { paths, profileExists, readState, updateState } from '../config/paths.js';
import { defaultImage } from '../docker/image.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TEMPLATE_DIR = join(__dirname, '..', '..', '..', 'templates');

export const DEFAULT_CODEX_PROFILE = 'codex';
// The two-container compose template maps host {{port}} -> container :8000, so
// the router always listens on 8000 internally. The Codex profile reuses host
// port 8000; its config server_port matches. This means the Codex and Claude
// router stacks are mutually exclusive on the host (only one can bind 8000 at a
// time) — `brick codex on` warns and asks to stop the other stack if it is up.
export const DEFAULT_CODEX_PORT = 8000;

/**
 * Materialize a ready-to-serve two-container default profile for OpenAI Codex
 * (complexity classifier + Brick router) if it does not exist yet. The router
 * runs the full skill router over the OpenAI pool and forwards via
 * /v1/chat/completions. Reuses the Claude two-container compose template
 * (parameterized by projectName/port). Returns the profile name.
 */
export async function ensureDefaultCodexProfile(): Promise<string> {
  const profile = DEFAULT_CODEX_PROFILE;
  if (profileExists(profile)) return profile;

  const pp = paths(profile);
  mkdirSync(pp.profileDir, { recursive: true, mode: 0o700 });

  // 1. Config (verbatim copy — preserves the skill_router + dynamic_effort block).
  const configTemplate = readFileSync(join(TEMPLATE_DIR, 'codex-default.config.yaml'), 'utf8');
  writeFileSync(pp.config, configTemplate, { mode: 0o600 });

  // 2. .env — random classifier bearer token (never leaves the local network).
  const classifierToken = randomBytes(32).toString('hex');
  writeFileSync(
    pp.env,
    `# Brick default Codex profile — generated by brick codex on.\n` +
    `# No provider API key needed: the client's OpenAI bearer is forwarded verbatim.\n` +
    `BRICK_CLASSIFIER_TOKEN=${classifierToken}\n`,
    { mode: 0o600 }
  );

  // 3. docker-compose.yml — reuse the two-container template (classifier + router).
  const composeTpl = readFileSync(join(TEMPLATE_DIR, 'claude-default.docker-compose.yaml.hbs'), 'utf8');
  const composeRendered = Handlebars.compile(composeTpl)({
    projectName: `brick-${profile}`,
    port: DEFAULT_CODEX_PORT,
    configPath: pp.config,
    useLocalClassifier: true,   // default profile ships the local classifier sidecar
    image: defaultImage(),
  });
  writeFileSync(pp.compose, composeRendered, { mode: 0o644 });

  if (!readState().activeProfile) updateState({ activeProfile: profile });

  return profile;
}
